name: 'Node CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
